config/routes.rb
Rails.application.routes.draw do

  resources :sermons
  
  devise_for :users

  resources :blogs

  resources :events
  
  root 'pages#home'

  get 'pages/home'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/our_pastor'

  get 'pages/our_church'

  get 'pages/give'

end

app/views/pages/contact.html.erb
    <section class="contact-hero-img">
      <div class="container">
        <h1>Contact</h1>
      </div>
    </section>

    <section class="contact">
      <div class="container group">
        <h2>Contact Us</h2>
        <section class="contact-methods">
          <h3>Call us:</h3>
          <a>(410) 757-2995</a>
          <h3>Email us:</h3>
          <a href="mailto:info@umbc.church">info@abumc.church</a>
          <h3>Write to us and visit us at:</h3>
          <a href="https://www.google.com/maps/dir//Asbury+Broadneck+United+Methodist,+Annapolis,+MD+21409/@39.0285058,-76.4870098,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x89b802a964fb69cf:0x55bd37656c10f733!2m2!1d-76.4519046!2d39.0284444">
            <address class="contact-page">
              <span>Asbury Broadneck United Methodist Church</span>
              <span>657 Broadneck Road,</span>
              <span>Annapolis MD, 21409</span>
            </address>
          </a>
        </section>
        <form id="contact-form">
        <h3>Send us a message:</h3>
          <input type="text" id="name" placeholder="Name" />
          <input type="text" id="email" placeholder="Emaill" />
          <textarea col="50" rows="10" placeholder="Message"></textarea>
          <input type="submit" value="Send" />
        </form>
      </div>
    </section>
    
    <section class="support-our-church">
      <div class="container">
        <h2>Support Our Church</h2>
        <div class="give-img">
          <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
        </div>
        <div class="learn-more-btn btn">
          <%= link_to 'Learn More', pages_give_path %>
        </div>
      </div>
    </section>

app/views/pages/give.html.erb
    <section class="give-hero-img">
      <div class="container">
        <h1>Tithes / Offerings</h1>
      </div>
    </section>

    <section class="give">
      <div class="container">
        <section class="tithe-section">
        <h2>How to Give</h2>
          <p>Asbury Broadneck United Methodist Church offers four convienient methods to <a class="give-link" href="why-give.html">support our church.</a> Please take advantage of one of these methods so that we can continue to do the work of our Lord and work in our community.</p>
        </section>

        <section class="tithe-section">
          <h2>Online Giving</h2>
          <p>With online giving anyone can pay tithes and give offerings to our church electronically. This means that you can pay tithes and offerings from your personal computer, your tablet, and your smart phone from anywhere. And because paying anything online electronically is always risky, we have encrypted our entire website to keep all the information on this site secure (notice the https). We have also decided to use <a href="http://stripe.com">Stripe</a> as our payment gateway for all electronic transactions on our website. <a href="http://stripe.com">Stripe</a> is the number one and the best service provider for all online transactions.</p>

          <div class="give-now-btn btn">
            <a href="#">Give Now</a>
          </div>
        </section>

        <section class="tithe-section">
          <h2>In Person</h2>
          <p>Every Sunday, we collect tithes and offerings during our Sunday Worship Serive. You can pay tithes and give offerings at the time it is announced in church.</p>
        </section>

        <section class="tithe-section">
          <h2>By Mail</h2>
          <p>You can pay tithes and give offerings through the mail.</p><p>Please mail it to our church at:</p>
          <address class="give-page">
          <span>Asbury Broadneck United Methodist Church</span>
          <span>657 Broadneck Road</span>
          <span>Annapolis MD 21409</span>
          </address>
          <p>Please also indicate if the funds are for tithes or offerings, and <span class="underline-text">do not mail cash.</span></p>
        </section>

        <section class="tithe-section">
          <h2>Through Your Bank</h2>
          <p>Asbury Broadneck United Methodist Church also accepts tithes and offerings paid through your bank. To learn how to pay tithes and offerings through your bank, <a href="#">click here</a> or the the button below.</p>
          <div class="learn-more-btn-give btn">
            <a href="#">Learn How</a>
          </div>
        </section>

        <section class="tithe-section">
          <h2>Questions about Giving?</h2>
          <p>Seamlessly morph low-risk high-yield intellectual capital without highly efficient web services. Seamlessly facilitate ethical metrics vis-a-vis collaborative communities. Proactively coordinate premier systems vis-a-vis e-business intellectual capital. Uniquely productize efficient materials vis-a-vis reliable leadership skills. Holisticly monetize web-enabled markets without technically sound users.</p>
          <div class="learn-more-btn-give btn">
            <a href="#">Ask Here</a>
          </div>
        </section>
      </div>
    </section>
    
    <section class="support-our-church">
      <div class="container">
        <h2>Support Our Church</h2>
        <div class="give-img">
          <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
        </div>
        <div class="learn-more-btn btn">
          <%= link_to 'Learn More', pages_give_path %>
        </div>
      </div>
    </section>

app/views/pages/history.html.erb
    <section class="history-hero-img">
      <div class="container">
        <h1>History</h1>
      </div>
    </section>

    <section class="history">
      <div class="container">
        <h1 class="section-title">Our Church History</h1>
        <p><span class="firstcharacter">A</span> sbury Broadneck United Methodist Church is an historical African American church.  It is reported that the church began  before 1851 when enslaved men of African decent started meeting at a placed called "Old School House Hill" to praise God in their own way.  This was before they could afford a church house.  But, the first church was built only yards from the original meeting location on St. Margaret's Road, which is now Meeting House Lane south of Route 50 east of Annapolis, MD.</p>

        <p>The trustees of the first church house were:  Henry Barnes, Philip Dorsey, Nance Hawkins, David Johnson  and Henry Wright.  On October 9, 1851 members of the church paid $60 for land and the first church building. The purchase was made from Samuel Richardson.</p>

        <p>The second church house was build on a piece of land purchased March 21, 1865.  An organization within the church known as "The Sons and Daughters of Joshua" donated the third piece of land where the current church is located.</p>

        <p>Early on the church was known as "Broadneck Church".  But as far back as the mid 1800's the church was under the leadership of the Asbury Annapolis Church, and the church was referred to as "Little Asbury".  The pastors of Asbury Annapolis ministered to the congregation at Little Asbury.  This lasted until 1873. The association lead to the church later being named "Asbury Broadneck Methodist Episcopal Church".  Reverend Isaac (Ike) E. Johnson, who was a lay pastor at the time, became the first  on-site pastor after the association with Asbury Annapolis.</p>
      </div>
    </section>

    <section class="support-our-church">
      <div class="container">
        <h2>Support Our Church</h2>
        <div class="give-img">
          <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
        </div>
        <div class="learn-more-btn btn">
          <%= link_to 'Learn More', pages_give_path %>
        </div>
      </div>
    </section>

app/views/pages/home.html.erb
    <section class="hero-img">
      <div class="container">
        <h1>Welcome to Asbury Broadneck United Methodist Church</h1>
      </div>
    </section>

    <section class="video-header">
      <div class="inner">
        <h1><span class="welcome-to">Welcome to</span> Asbury Broadneck United<span class="welcome-to"> Methodist Church</span></h1>
      </div>
      <%= video_tag("https://s3.amazonaws.com/asburychurch/church.mp4", :controls => false, :id =>"video-background", :autoplay => true, :autobuffer => true, :loop => true) %>
    </section>

    <section class="intro-text">
      <div class="container">
        <h2>Come Join Us</h2>
        <p>We invite you to come and worship with us, as we offer praises to the God of salvation. We are involved in many ministries at Asbury Broadneck United Methodist Church. There is room for you and your family. Please consider becoming a part of our efforts. There is a place, a ministry, and work for you here at Asbury Broadneck United Methodist Church.</p>
        <div class="visit-us-btn btn">
          <a href="#">Visit Us</a>
        </div>
      </div>
    </section>

    <section id ="google-ma" class="times-location group">
      <div class="times-and-location-section group service-times-container">
        <div class="service-times service-container">
          <div class="times">
            <h2>Church Service Times</h2>
            <p>Sunday Worship | 10:00 am</p>
            <p>Sunday School | 9:45 am</p>
          </div>
          <div class="location">
            <h2>Location</h2>
            <address>
            <span>657 Broadneck Rd</span>
            <span>Annapolis, Maryland 21409</span>
            </address>
          </div>
        </div>
        <div id="map"></div>
      </div>
      <div class="get-directions-btn btn">
        <a href="https://www.google.com/maps/dir//Asbury+Broadneck+United+Methodist,+Annapolis,+MD+21409/@39.0285058,-76.4870098,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x89b802a964fb69cf:0x55bd37656c10f733!2m2!1d-76.4519046!2d39.0284444">Get Directions</a>
      </div>
    </section>

    <section class="upcoming-events">
      <div class="container">
      <h2>Upcoming Events</h2>
      <section class="event group">
        <div class="event-date">
          <div class="event-month">Apr</div>
          <div class="event-day">3</div>
        </div>
        <div class="event-details">
          <h1 class="event-title">Pastor's Ball</h1>
          <address>
            657 Broadneck Road Annapolis Maryland 21409
          </address>
          <div class="event-info">Suspendisse tincidunt laoreet vestibulum? Quisque posuere ut quam nec egestas? Morbi facilisis ex ac magna aliquet, ac feugiat nibh faucibus. Curabitur feugiat finibus eros, vel porta nunc vestibulum quis. Praesent iaculis fringilla egestas. Proin facilisis dapibus quam et dignissim. Sed placerat libero posuere magna pharetra, id condimentum eros suscipit.</div>
          <a href="#" class="details">Details
            <i class="fa fa-long-arrow-right"></i>
          </a>
        </div>
      </section>
      <section class="event group">
        <div class="event-date">
          <div class="event-month">May</div>
          <div class="event-day">12</div>
        </div>
        <div class="event-details">
          <h1 class="event-title">Women's  Ministry Meeting</h1>
          <address>
            657 Broadneck Road Annapolis Maryland 21409
          </address>
          <div class="event-info">Suspendisse tincidunt laoreet vestibulum? Quisque posuere ut quam nec egestas? Morbi facilisis ex ac magna aliquet, ac feugiat nibh faucibus. Curabitur feugiat finibus eros, vel porta nunc vestibulum quis. Praesent iaculis fringilla egestas. Proin facilisis dapibus quam et dignissim. Sed placerat libero posuere magna pharetra, id condimentum eros suscipit.</div>
          <a href="#" class="details">Details
            <i class="fa fa-long-arrow-right"></i>
          </a>
        </div>
      </section>
      <section class="event group">
        <div class="event-date">
          <div class="event-month">Jun</div>
          <div class="event-day">14</div>
        </div>
        <div class="event-details">
          <h1 class="event-title">Annapolis Food Drive</h1>
          <address>
            657 Broadneck Road Annapolis Maryland 21409
          </address>
          <div class="event-info">Suspendisse tincidunt laoreet vestibulum? Quisque posuere ut quam nec egestas? Morbi facilisis ex ac magna aliquet, ac feugiat nibh faucibus. Curabitur feugiat finibus eros, vel porta nunc vestibulum quis. Praesent iaculis fringilla egestas. Proin facilisis dapibus quam et dignissim. Sed placerat libero posuere magna pharetra, id condimentum eros suscipit.</div>
          <a href="#" class="details">Details
            <i class="fa fa-long-arrow-right"></i>
          </a>
        </div>
      </section>
      <div class="see-more-btn btn">
        <%= link_to 'See More', events_path %>
      </div>
    </section>

    <section class="prayer-requests">
      <div class="container">
        <h2>Have a prayer request?</h2>
        <p>Fill out this form</p>
        <form id="prayer-request">
          <input id="name" type="text" placeholder="Name"/>
          <input id="email" type="email" placeholder="Email"/>
          <textarea col="10" rows="10" placeholder="Please tell us how we can help"></textarea>
          <input type="submit" value="Send" />
        </form>
      </div>
    </section>

    <section class="latest-sermons">
      <div class="container">
        <h2>Latest Sermons</h2>
        <section class="sermon">
          <div class="group">
            <div class="sermon-info">
              <h1 class="sermon-title">The Joy of the Lord</h1>
              <p class="sermon-author">Rev. Tillett, </p>
              <p class="sermon-date">January 24th, 2016</p>
            </div>
          </div>
          <div class="sermon-player">
            <audio class="audio-player" src="audio/Vacationer - Good as New.mp3" style="width:100%; height:60px;"></audio>
          </div>
        </section>
        <section class="sermon">
          <div class="group">
            <div class="sermon-info">
              <h1 class="sermon-title">The Joy of the Lord</h1>
              <p class="sermon-author">Rev. Tillett, </p>
              <p class="sermon-date">January 24th, 2016</p>
            </div>
          </div>
          <div class="sermon-player">
            <audio class="audio-player" src="audio/Vacationer - Good as New.mp3" style="width:100%; height:60px;"></audio>
          </div>
        </section>
        <section class="sermon">
          <div class="group">
            <div class="sermon-info">
              <h1 class="sermon-title">The Joy of the Lord</h1>

              <p class="sermon-author">Rev. Tillett, </p>
              <p class="sermon-date">January 24th, 2016</p>
            </div>
          </div>
          <div class="sermon-player">
            <audio class="audio-player" src="audio/Vacationer - Good as New.mp3" style="width:100%; height:60px;"></audio>
          </div>
        </section>
        <div class="hear-more-btn btn">
          <a href="sermons.html">Hear More</a>
        </div>
      </div>
    </section>

    <section class="blog">
      <div class="container">
        <h2>The Pastor's Blog</h2>
        <% @blogs.each do |blog| %>
          <section class="blog-entry group">
            <%= image_tag blog.image.url(:large), class:"blog-img" %>
              <div class="blog-details">
                <h1 class="blog-title"><%= blog.title %></h1>
                <%= image_tag(blog.user.avatar, class: "blog-author-img") %>
                <p class="author"><%= blog.user.user_name %></p> |
                <span class="blog-date"><%= blog.created_at.strftime("%d %b. %Y") %></span>
                <div class="blog-excerpt"><%= truncate(blog.post, length: 220) %></div>
                <div class="read-more">
                <%= link_to 'Read More', blog %>
                <i class="fa fa-long-arrow-right"></i>
              </div>
              <% if blog.user == current_user %>
                <div class="show-edit-delete-btns">
                  <%= link_to 'Edit', edit_blog_path(blog) %> |
                  <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              <% end %>
            </div>
          </section>
        <% end %>
        <div class="read-more-btn btn">
        <%= link_to 'Read More', blogs_path %>
        </div>
      </div>
    </section>

    <section class="support-our-church">
      <div class="container">
        <h2>Support Our Church</h2>
        <div class="give-img">
          <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
        </div>
        <div class="learn-more-btn btn">
          <%= link_to 'Learn More', pages_give_path %>
        </div>
      </div>
    </section>

app/views/pages/our_church.html.erb
<h1>Pages#our_church</h1>
<p>Find me in app/views/pages/our_church.html.erb</p>

app/views/pages/our_pastor.html.erb
    <section class="pastor-hero-img">
      <div class="container">
        <h1>Our Pastor</h1>
      </div>
    </section>

    <section class="pastor">
      <div class="container">
        <h2>Rev. Stephen A. Tillett</h2>

        <div class="rev-section group">
      
          <%= image_tag("tillet.jpg", class: "pastor-img") %>

          <ul class="churches-served">
            <h3>Churches Served</h3>
            <li>Asbury Broadneck, Annapolis, MD (July 1, 2004 to Present)</li>
            <li>Mt. Zion, Baltimore, MD (July 1, 1996 to June 30, 2004)</li>
            <li>Petworth, Washington, DC (July 1, 1992 to June 30, 1996)</li>
            <li>Bradbury Heights, Washington, DC  (Jan. 1, 1990 to June 30,1996)</li>
          </ul>

        </div>

        <p><span class="firstcharacter">S</span> tephen Andrew Tillett was born and reared in Washington, D.C. He graduated from St. John's College High School in Washington. He received his foundational Christian nurture and education at Asbury United Methodist Church in Washington, D.C.</p>

        <p>Brother Tillett received a B.A. from the School of Government and Public Administration at The American University. He attended the Howard University School of Divinity and received the Master's of Divinity degree.</p>

        <p>He has served as the pastor of First United Methodist Church (UMC), Bradbury Heights in Washington, D.C. He also served as the pastor of Petworth UMC also in Washington.</p>

        <p>After serving these two churches, Brother Tillett was appointed to serve as pastor of Mt. Zion UMC in Baltimore, MD in July 1996.</p>

        <p>Another opportunity for ministry presented itself at around the same time. Brother Tillett was commissioned as a Chaplain in the Air National Guard in December 1996. Lt Col Tillett served as the Wing Chaplain for the 113th Air Wing, which is located at Andrews Air Force Base in Maryland, where he functioned as the senior pastor for a “congregation” of over eleven hundred men and women. He was also the Deputy State Chaplain for Air for the DC National Guard. In May of 2012, Lt Col Tillett transferred to the US Air Force Reserve as an IMA (Individual Mobilization Augmentee) to the Wing Chaplain at the 4th Fighter Wing as Seymour Johnson AFB in Goldsboro, NC.</p>

        <p>In July 2004, Rev. Tillett was appointed as the pastor of <%= link_to 'Asbury Broadneck UMC in Annapolis, MD.', pages_home_path %></p>

        <p>He has been blessed by God with three children, Drew (Stephen A. II) an aspiring musician and music producer and Lena (Charlena), who is pursuing a Master’s degree in Broadcast Journalism at New York University. He and his wife, Sherita, are the proud parents of Sophia Grace.</p>

        <p>He continues to be led by the advice of his late grandmother, Mrs. Josephine Brooks Johnson, who would always say, "say your prayers and do what's right." He hopes our ancestors take comfort in the things we aspire to today.</p>

        <p>A key area of focus of the ministry is to address the inequities in the criminal justice system by establishing a comprehensive and sustainable ministry to those who are incarcerated and mentorship for their young family members. 
        One of his favorite scriptures is Psalm 146:1-4 (NIV):</p>

        <ol>
          <li>Praise the LORD. Praise the LORD, O my soul.</li>
          <li>I will praise the LORD all my life; I will sing praise to my God as long as I live.</li>
          <li>Do not put your trust in princes, in mortal men, who cannot save.</li>
          <li>When their spirit departs, they return to the ground; on that very day their plans come to nothing.</li>
        </ol>

        <p>His favorite pastimes include bowling, reading, writing, current events, singing and travel.</p>
      
      </div>
    </section>

    <section class="support-our-church">
      <div class="container">
        <h2>Support Our Church</h2>
        <div class="give-img">
          <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
        </div>
        <div class="learn-more-btn btn">
          <%= link_to 'Learn More', pages_give_path %>
        </div>
      </div>
    </section>