config/routes.rb
Rails.application.routes.draw do

  resources :sermons
  
  devise_for :users

  resources :blogs

  resources :events
  
  root 'pages#home'

  get 'pages/home'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/our_pastor'

  get 'pages/our_church'

  get 'pages/give'

end

app/models/sermon.rb
class Sermon < ActiveRecord::Base

	has_attached_file :audio, 
										:bucket => ENV['bucket'],
 										:storage => :s3, 
 										:s3_region => 'us-east-1'

	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3', 'audio/mpeg']

end  

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController
  before_action :set_sermon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /sermons
  # GET /sermons.json
  def index
    @sermons = Sermon.all
  end

  # GET /sermons/1
  # GET /sermons/1.json
  def show
  end

  # GET /sermons/new
  def new
    @sermon = Sermon.new
  end

  # GET /sermons/1/edit
  def edit
  end

  # POST /sermons
  # POST /sermons.json
  def create
    @sermon = Sermon.new(sermon_params)

    respond_to do |format|
      if @sermon.save
        format.html { redirect_to @sermon, notice: 'Sermon was successfully created.' }
        format.json { render :show, status: :created, location: @sermon }
      else
        format.html { render :new }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sermons/1
  # PATCH/PUT /sermons/1.json
  def update
    respond_to do |format|
      if @sermon.update(sermon_params)
        format.html { redirect_to @sermon, notice: 'Sermon was successfully updated.' }
        format.json { render :show, status: :ok, location: @sermon }
      else
        format.html { render :edit }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sermons/1
  # DELETE /sermons/1.json
  def destroy
    @sermon.destroy
    respond_to do |format|
      format.html { redirect_to sermons_url, notice: 'Sermon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sermon
      @sermon = Sermon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sermon_params
      params.require(:sermon).permit(:title, :scripture, :description, :audio)
    end
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/sermons/_form.html.erb
<%= form_for @sermon, :html => { :multipart => true }  do |f| %>
  <% if @sermon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sermon.errors.count, "error") %> prohibited this sermon from being saved:</h2>

      <ul>
      <% @sermon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :scripture %><br>
    <%= f.text_field :scripture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :audio %><br>
    <%= f.file_field :audio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sermons/edit.html.erb
<div class="container">
	<h1>Editing Sermon</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @sermon %> |
	<%= link_to 'Back', sermons_path %>
</div>

app/views/sermons/index.html.erb
<section class="sermon-hero-img">
  <div class="container">
    <h1>Sermons</h1>
  </div>
</section>
<div class="container">

  <section class="sermons">
    <div class="container">
      <h2>Recent Sermons</h2>
      <div class="btn-link">
        <% if user_signed_in? %>
          <%= link_to 'Add New Sermon', new_sermon_path %>
        <% end %>
      </div>
      <section class="sermon">
        <% @sermons.each do |sermon| %>
          <div class="group">
            <div class="sermon-info">
              <h1 class="sermon-title"><%= sermon.title %></h1>
              <p class="sermon-author">Rev. Tillett, </p>
              <p class="sermon-date"><%= sermon.created_at.strftime("%b %d. %Y") %></p>
              <p class="sermon-scriptures"><%= sermon.scripture %></p>
            </div>
          </div>
          <div class="sermon-player">
            <%= audio_tag(sermon.audio.url, class: "audio-player", style: "width:100%; height:60px;") %>
          </div>
          <div class="read-more">
            <%= link_to 'More', sermon %>
            <i class="fa fa-long-arrow-right"></i>
          </div>
          <div class="show-edit-delete-btns">
            <%= link_to 'Edit', edit_sermon_path(sermon) %> |
            <%= link_to 'Destroy', sermon, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </section>
      <div class="hear-more-btn btn">
        <a href="#">Hear More</a>
      </div>
    </div>
  </section>
</div>
<%= render "layouts/support" %>

app/views/sermons/new.html.erb
<div class="container">
	<h1>New Sermon</h1>

	<%= render 'form' %>

	<%= link_to 'Back', sermons_path %>
</div>

app/views/sermons/show.html.erb
<section class="sermon-hero-img">
  <div class="container">
    <h1>Sermons</h1>
  </div>
</section>
<div class="container">
	<p>
	  <strong>Title:</strong>
	  <%= @sermon.title %>
	</p>

	<p>
	  <strong>Scripture:</strong>
	  <%= @sermon.scripture %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @sermon.description %>
	</p>

	<p>
	  <strong>Sermon:</strong>
	  <%= audio_tag @sermon.audio %>
	</p>

	<%= link_to 'Edit', edit_sermon_path(@sermon) %> |
	<%= link_to 'Back', sermons_path %>
</div>