config/routes.rb
Rails.application.routes.draw do

  resources :sermons
  
  devise_for :users

  resources :blogs

  resources :events
  
  root 'pages#home'

  get 'pages/home'

  get 'pages/contact'

  get 'pages/history'

  get 'pages/our_pastor'

  get 'pages/our_church'

  get 'pages/give'

end

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <div class="container">
        <p>Asbury Broadneck United Methodist Church</p>
        <p> &copy; <%= Time.now.year %></p>
      </div>
    </footer>

    <%= render "layouts/scriptFiles" %>
  </body>
</html>

app/views/layouts/_header.html.erb
    <header>
      <div class="header group">
        <%= link_to 'ABUMC', root_path, id: "logo" %></a>
        <div id="menu-btn">
          <i class="fa fa-bars"></i>
        </div>
      </div>
      <nav>
        <ul class="nav">
          <li><a class="dropdown-menu" href="#">About</a>
            <ul class="dropdown-content">
            <li><%= link_to 'History', pages_history_path %></li>
            <li><%= link_to 'Our Pastor', pages_our_pastor_path %></li>
            <li></li>
            <li><%= link_to 'Giving', pages_give_path %></li>
              <li><a href="https://www.google.com/maps/dir//Asbury+Broadneck+United+Methodist,+Annapolis,+MD+21409/@39.0285058,-76.4870098,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x89b802a964fb69cf:0x55bd37656c10f733!2m2!1d-76.4519046!2d39.0284444">Directions</a></li>
            </ul>
          </li>
          <li><%= link_to 'Sermons', sermons_path %></li>
          <li><%= link_to 'Events', events_path %></li>
          <li><%= link_to 'Blog', blogs_path %></li>
          <li><%= link_to 'Give', pages_give_path %></li>
          <li><a href="contact.html">Contact</a></li>
          <% if user_signed_in? %>
            <li><%= image_tag(current_user.avatar.url(:thumb), class: "current-user-img") %></li>
            <li><%= link_to " Log out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit",  edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>

app/views/layouts/_scriptFiles.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDELpr4WJAWQr6kkRQiGyT6BNFt6nmKz4o&amp;callback=initMap" async="" defer=""></script>

<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/src/markerwithlabel.js"></script>

    <script src="js/mediaelement-and-player.min.js"></script>
    <script src="js/mejs-feature-fontawesome.min.js"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
  function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
  e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  e.src='https://www.google-analytics.com/analytics.js';
  r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>

app/views/layouts/_support.html.erb
<section class="support-our-church">
  <div class="container">
    <h2>Support Our Church</h2>
    <div class="give-img">
      <%= link_to image_tag("give-btn.svg"), pages_give_path %></a>
    </div>
    <div class="learn-more-btn btn">
      <%= link_to 'Learn More', pages_give_path %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="">
<head>
	<meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <title>ChurchSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- <script src="js/vendor/modernizr-2.8.3.min.js"></script> -->
</head>
	<body>
		<!--[if lt IE 8]>
	        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	    <![endif]-->

	  <!-- Add your site or application content here -->
	  
		<div id="flash">
			<p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>
		</div>

	  <%= render "layouts/header" %>

		<%= yield %>

		<%= render "layouts/footer" %>

	</body>
</html>